# Generated by Django 4.2.3 on 2024-01-31 06:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeApi.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('current_sem', models.IntegerField()),
                ('passing_year', models.CharField(max_length=10)),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeApi.department')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeApi.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeApi.department')),
            ],
        ),
    ]
